### ISSUE TITLE
Issue with armor

### ISSUE THREAD

**Issue by MarioHunter07** [Leronus/mOres#10]
When equipping any piece of armor from the mod it causes instant loss of the night vision effect. Game version is 1.19.2 and mod version is 4.3.3

**Comment by Leronus** [comment]
Thank you for bringing this to my attention. Will be fixed next release.

**Comment by Leronus** [comment]
Fixed on 28/05/23 per [Release v4.3.4](https://legacy.curseforge.com/minecraft/mc-mods/mores-by-its-infinite/files/4555983)

**Comment by Toastr125** [comment]
Any chance this fix could be backported to 1.18.2? I'm making a modpack on that version (using mOres 3.2.3) and noticed the same bug happening. I tested with several other effects - it only happens with night vision and happens when equipping any piece of armor from this mod.
