### ISSUE TITLE
Shields not defending.

### ISSUE THREAD

**Issue by thelunacodes** [Leronus/mOres#12]
I'm unable to defend myself using the shields. 

Info:

Win 10
Minecraft 1.20.1
mOres 5.2.0
CurseForge client

**Comment by Leronus** [comment]
The shields only block a partial amount of damage. The graphene shield blocks all damage. To disable this behaviour, you'll have to set it to false in the mores config file, located in the config folder of your minecraft installation.

**Comment by thelunacodes** [comment]
The shields not having an animation for it being used is proposital?

**Comment by Leronus** [comment]
Ah I had not noticed this issue, thanks for bringing it to my attention. I was not able to deduct this from your initial comment. I am working on an update as we speak, it will be released very soon. Thank you for your patience & playing my mod :)

**Comment by Leronus** [comment]
Fixed in [Release v5.3.0](https://legacy.curseforge.com/minecraft/mc-mods/mores-by-its-infinite/files/4713077)
