### ISSUE TITLE
All the Latest Minecraft and Forge releases (no alpha or beta): All pickaxes are not working as of 10/16/2023

### ISSUE THREAD

**Issue by Sparrow231129** [Leronus/mOres#17]
I added about 40 mods to my forged Minecraft personal, individual, no server launch Modpack. All my pickaxes stopped functioning. No speed, no drops. I disabled the new mods and then launched and tested pickaxes. They worked. I proceeded to enable the new mods one at a time, launch, test, quit, repeat until I found the one that broke the pickaxes. Sad to say, it was mOres. I know you have fixed this before, and I know that Forge has stopped using whatever it was using to keep your mod up-to-date. They did this because they got hacked and virused. They found the breach and fixed it, but they also have made it more difficult on mod creators to prevent a recurring problem. Please do not abandon Forge. I know it puts a burden on you, but Forge is an essential way for me to make my worlds "perfect". Please, post a repaired/renewed update to Forge, if for no other reason than I'm asking so nicely.

**Comment by Leronus** [comment]
Dear Sparrow,

Edit: 
I was able to reproduce the issue in the latest version of mOres ([Release v5.4.1](https://www.curseforge.com/minecraft/mc-mods/mores-by-its-infinite/files/4793706))
My apologies! I had completely missed this. Thank you for bringing this to my attention, I will be working on an update as we speak.

As for Forge, I don't think I've ever said I would abandon it. I have updated the mod up to a week ago for Forge. And I'll continue to do so. Forge will remain the preferred modloader for the foreseeable future, so you don't have to worry about that.

I will resolve this issue and release the updated version sometime today or tomorrow. Thank you for your patience and 
for playing my mod <3

Kind regards,
Leronus

**Comment by Leronus** [comment]
Update: I was able to reproduce the issue in the latest version of mOres [Release v5.4.1](https://www.curseforge.com/minecraft/mc-mods/mores-by-its-infinite/files/4793706)) , my apologies! I had completely missed this. Thank you for bringing this to my attention, I will be working on an update as we speak.

**Comment by Leronus** [comment]
It is sadly proving more difficult than I had initially anticipated. Luckily it's only in the 1.20.2 versions. I have temporarily archived them to prevent further issues. I'm hoping to release a fix sometime this week rather.

**Comment by Leronus** [comment]
I have taken another look at the issue and have finally managed to resolve the problem :)
You may download the update [here](https://legacy.curseforge.com/minecraft/mc-mods/mores-by-its-infinite/files/4839331)

Thanks again for playing my mod <3
