### ISSUE TITLE
How can i get Onyx?

### ISSUE THREAD

**Issue by SergioModified** [Leronus/mOres#19]
Hello, I realized that to make graphene I need Onyx, when I went to look for how to get it, no information about it appeared and the wiki does not say if it is made in AlloyFurnace. 
Here I show what "JEI" tells me to get the Onyx of the mod

**Aight, all the problems were solved: i discovered that Onyx it's in the END. The armors give the buff ones that the mod proposes, but some do not show the enchantment, I will still leave this here in case this information is useful to any other player**

edit: I realized that the buffs that give armor only apply to versions higher than 1.16.5 and I was wondering if they could be added to 1.12.2
![2024-01-12_20 28 46](https://github.com/Leronus/mOres/assets/156486951/9346f936-c1f6-467b-9078-a61be808c1ef)

**Comment by Leronus** [comment]
Ohh fascinating. I suppose you're referring to the wither effect on the onyx weapons? As far as I recall onyx armor does not have any effects

**Comment by Leronus** [comment]
Sorry for my late response I had not gotten a notification for your message!

**Comment by Leronus** [comment]
I can see about adding the armor effects to 1.12.2 in the future, but it is very unlikely. I had not read that part of your issue before. I am considering this issue as closed since 1.12.2 is in fact unsupported. Again, if I have the time I'll look into it though.
