### ISSUE TITLE
new armor doesnt actually do anything....

### ISSUE THREAD

**Issue by SourPoultry** [Leronus/mOres#23]
i did a controlled experiment where i jumped off a five-block tower with graphene armor and without any armor, both dealed me 1 heart of damage. probably just a bug. also armor doesnt wear out.

effects do work tho.

**Comment by Leronus** [comment]
Armor does not decrease fall damage in vanilla Minecraft. My mod does not change this, therefore it is not a bug.
The armor does wear out, but has a very high durability so it won't wear out quickly.
