### ISSUE TITLE
Ore generation

### ISSUE THREAD

**Issue by Raph463467** [Leronus/mOres#9]
### This mod has tons of potential, it'd be great if **Modpack Creators** could tweak it to suit their needs

I like the way we can **customise**  layers in wich ores will generate. Hadn't seen that in other ore generating mods and its pretty neat and easy to grasp. But Personnaly, I'd want to lower spawns of some ores to better fit my modpack's progration pace, but can't seem to find within the config files a way to do so.

to solve this, we could add a  **variable for spawn rates** to each layer and per ore. With _relevant metrics_ as perhaps :

 

- [ ] -**spawn attempts** per chunk of the **targeted layer**

- [ ] -**size** of ore deposits  : _min/max_

possible complications ? 

- having a wide or narrow layer would affect the disparity of spawn attempts)
- dunno how the code is organized, it could end up beeing a lot of work

Thank you for your attention. Have a nice one

**Comment by Leronus** [comment]
Yes as of now I believe only the height can be adjusted in the config ('mores-common.toml'), I plan to add the so called **veins per chunk** in the config as well. I also believe there is a certain _pSize_ (I believe thats the size of ore deposit you were referring to) that adjusts the ore veins, which I'll probably also add to the config at some point in the future. Please note that I have worked on this mod completely solo so it takes a lot of time to update.

Thanks for the compliment and I'm glad you're enjoying my mod :)
You'd help me out greatly if you could share it to anyone who is interested. Thanks again my dude!

**Comment by Raph463467** [comment]
Yeah I get that, it's tough to do this on your own. You got me right, and as a mater of fact I 've got quite a few friends that will enjoy the modpack I'm working on. + another one that is trying mod stuff on it's own too, I'll show him you mod so he might be able to integrate it to the ones he is making :)

Good luck, I'll be waiting that update x)
